# pragma once

#define CONFIG_WL_SECTOR_SIZE   4096
#define CONFIG_LOG_DEFAULT_LEVEL 3
#define CONFIG_PARTITION_TABLE_OFFSET 0x8000
#define CONFIG_ESPTOOLPY_FLASHSIZE "4MB"
#define CONFIG_FATFS_MAX_LFN 255
#define CONFIG_FATFS_LFN_HEAP 1
